Repository Kuama-IT/ios-location-listener, pull requests merged in 2021-06, with the labels that each got.

#4 Location reading interval
  ios-location-listener/Classes/LocationUtility.swift
  ios-location-listener/Classes/StreamLocation.swift
  ios-location-listener/Classes/UserNotificationDelegate.swift
Labels: size/L

#5 Removed unused files
  ios-location-listener/Classes/LocationUtility.swift
  ios-location-listener/Classes/UserNotificationDelegate.swift
Labels: size/L

#7 Fix the init and add a start function that throws an error
  ios-location-listener/Classes/StreamLocation.swift
Labels: size/M

#8 Version 0.2.0
  ios-location-listener/Classes/StreamLocation.swift
Labels: release, size/M

#9 Update ios-location-listener.podspec
  ios-location-listener.podspec
Labels: size/XS

#10 Version 0.2.0
  ios-location-listener.podspec
Labels: size/XS
